### PR TITLE
actions: do not fail CI upon codecov error

### PR DESCRIPTION
**Pull request by Wenzel**
@rageagainsthepc will this fix our CI ?

### CODE REVIEW

**Comment by Wenzel** [comment]
I just found this flag by chance while reviewing the CI configuration.
Maybe it works

**Comment by rageagainsthepc** [comment]
Huh, I knew about this flag, but I was convinced that it only refers to the github action where it is set. Still, I would like to know why codecov has errors in the first place. Oh well... :shrug:

**Comment by Wenzel** [comment]
So, it didn't work :crying_cat_face: 
https://github.com/Wenzel/libmicrovmi/pull/70

**Comment by Wenzel** [comment]
Looking at https://github.com/codecov/codecov-action:

_Specify if CI pipeline should fail when Codecov runs into errors during upload._

So wrong flag :)

**Comment by Wenzel** [comment]
See https://github.com/Wenzel/libmicrovmi/pull/99

**Comment by rageagainsthepc** [comment]
> Looking at https://github.com/codecov/codecov-action:
> 
> _Specify if CI pipeline should fail when Codecov runs into errors during upload._
> 
> So wrong flag :)

So my initial understanding of this flag was correct after all. :)

**Pull request merged**
