### PR TITLE
actions: test C API

### PR DESCRIPTION
**Pull request by Wenzel**
Following https://github.com/Wenzel/libmicrovmi/pull/43

We should add CI test before merging a PR in the future.

cc @rageagainsthepc

### CODE REVIEW

**Comment by Wenzel** [comment]
@rageagainsthepc turns out I had to fix the Makefile ! :-)

The order of GCC arguments matter, especially the linking order, always put them at the end of the command line:
https://www.quora.com/Why-does-order-of-parameters-supplied-to-GCC-matter

**Comment by rageagainsthepc** [comment]
Huh, it actually does ring a bell, but I've totally forgotten about it.

**Comment by Wenzel** [comment]
@rageagainsthepc the funny thing is that it actually compiled in my Debian 10 VM :man_shrugging: 

Older version of GCC, different behavior I guess..

**Comment by rageagainsthepc** [comment]
That can't be it. I've successfully compiled it on Fedora 31 with a very recent version of GCC. 🤔

**Comment by Wenzel** [comment]
Well, on my ubuntu 19.10, it didn't.

Important thing is that we respect gcc's command line expectations.

**Pull request merged**
