### PR TITLE
cargo: pin dependencies

### PR DESCRIPTION
**Pull request by Wenzel**

### CODE REVIEW

**Comment by rageagainsthepc** [comment]
Imho I would have left the dependency pinning unchanged. The problem instead was that you have disregarded semantic versioning rules by adding breaking changes in a patch version.

**Comment by Wenzel** [comment]
Yes, i released a patch which should have been a major release since it broke the public API.

**Comment by rageagainsthepc** [comment]
Rust guidelines actually allow breaking changes in minor version increments if the major version is zero.

**Comment by Wenzel** [comment]
Is there a rust tool that would automatically i'crement the release version, based on the changes in the public API

**Comment by rageagainsthepc** [comment]
I don't know 🤔

**Comment by Wenzel** [comment]
in the meantime i should release a new minor version for the kvmi crate, and remove the pin.

**Pull request merged**
